### ISSUE TITLE
Support for core OVE services in Python API wrapper

### ISSUE THREAD

**Issue by dsigdosystem** [ove/ove-sdks#1]
<a href="https://github.com/jamesscottbrown"><img src="https://avatars1.githubusercontent.com/u/338833?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jamesscottbrown](https://github.com/jamesscottbrown)**
_Monday Sep 24, 2018 at 15:53 GMT_
_Originally opened as https://github.com/dsi-icl/ove/issues/53_

----

**Comment by jamesscottbrown** [comment]
The core Asset Manager service and Image Tile Generator service now have APIs that the Python library should be able to interact with.

**Comment by senakafdo** [comment]
This is no longer relevant as we have a new [Asset Manager](https://github.com/ove/ove-asset-manager).
