### ISSUE TITLE
Support getting complete state of a section

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-sdks#14]
There should a method to get the current complete state of any section.

**Comment by jamesscottbrown** [comment]
This is currently blocked as the  apps all provide the state at the old route `/{sectionId}/state`, rather than `/instances/{instanceId}/state` or `/sections/{sectionId}/state`.

**Comment by senakafdo** [comment]
I would suggest that we take an approach similar to OVE core, which supports both formats as backwards compatibility. Alternative option would be to implement this against the existing API route, and report a blocker that needs to be fixed before the next OVE release.
