### ISSUE TITLE
Support DZI tile sources in Python API

### ISSUE THREAD

**Issue by dsigdosystem** [ove/ove-sdks#2]
<a href="https://github.com/jamesscottbrown"><img src="https://avatars1.githubusercontent.com/u/338833?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jamesscottbrown](https://github.com/jamesscottbrown)**
_Tuesday Sep 25, 2018 at 14:58 GMT_
_Originally opened as https://github.com/dsi-icl/ove/issues/58_

----

The Python API current only supports states of the ``images`` app that use a single image file rather than a DZI tile source (for which the  ``tileSource`` object has no ``url`` attribute).

**Comment by dsigdosystem** [comment]
<a href="https://github.com/senakafdo"><img src="https://avatars3.githubusercontent.com/u/3415383?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [senakafdo](https://github.com/senakafdo)**
_Tuesday Sep 25, 2018 at 15:00 GMT_

----

Better to consider the full list at https://openseadragon.github.io/#examples-and-features.

**Comment by senakafdo** [comment]
This is no longer relevant as we have a new [Asset Manager](https://github.com/ove/ove-asset-manager).
