### ISSUE TITLE
Python SDK needs to be updated to match latest changes

### ISSUE THREAD

**Issue by senakafdo** [ove/ove-sdks#6]
Below is a list of things that have changed.

- [ ] OVE Core has newer APIs around groups, space geometries and reading and updating details of multiple sections.
- [ ] Older OVE Core APIs now return more information as a part of their responses. For example, retrieving information of a section gives you complete geometry information and details of space/state.
- [ ] All OVE apps now have common operations for zoom/pan, which can be supported by the Python SDK.
- [ ] There are a number of new apps: Audio, SVG, PDF, Whiteboard, Controller, Replicator etc.
- [ ] The OVE core services have also evolved and we no longer have the present format of an Image Tiles service.
- [ ] The OVE project no longer has Data Observatory specific configurations and none of them should be a part of the standard Python SDK. It instead should be able to connect to a deployed OVE instance and produce corresponding configurations, if possible.

**Comment by jamesscottbrown** [comment]
I think it makes sense to wait until the API issues in https://github.com/ove/ove/issues/96 have been resolved, and then update the Python library all at once.

If the library is updated now, it is expected to break again imminently when the API is updated.

**Comment by senakafdo** [comment]
So, there are two sides to this. 

ove/ove#96, is not something we can do immediately and then settle down. It is an issue that will be fixed iteratively over time and before we go about doing that we need to have a clear picture of what the overall API would look like. This cannot be done until almost all of the OVE components are complete and in place.

The Python SDK would not be usable unless it supports the APIs as it stand, but yes it will be repetitive work to keep updating it. OTOH, without components like the Python SDK using the APIs we cannot finalise it either. Given that we are taking an agile approach to this, it is not going to be a one off task to fix the API and then do everything after it.

If we therefore delay the work on the Python SDK, the chances are that it would not be well tested for 1.0.0.

**Comment by jamesscottbrown** [comment]
I agree that we will likely need to iteratively refine the API.

That is why I think we need to do an API iteration now, to fix the issues that have been identified so far [in addition to avoiding wasted effort on the Python library]. 

We can then use the improved API in the Python library/OVE loader/OVE Editor, and see whether any new issues arise as they are being developed, without being distracted by the ones that are already known. After all of the functionality for 1.0.0 is implemented, we can make a further synoptic assesement of all of the APIs together.

> If we therefore delay the work on the Python SDK, the chances are that it would not be well tested for 1.0.0.

If we update the API + Python library now, there will be more time for testing than if we delay all the API changes until just before 1.0.0, then change everything and hurriedly update the Python library to match before the release.

**Comment by senakafdo** [comment]
You have a point. 

But, it is counterproductive to do an API interation until at least all of its key components are working with the existing API, such that we have a starting point and also have a clear picture of what the API should look like. This would therefore not happen for a while.

**Comment by jamesscottbrown** [comment]
A major part of the Data Observatory specific configurations is the list of port numbers: this will be removed once we are proxying our microservices properly, rather than assigning them to a port range that differs between installations.

**Comment by jamesscottbrown** [comment]
I am closing this issue as I have split these suggestions into separate issues.
